README.md, cmd/non-etcd-apiserver/main.go, pkg/apis/cluster/v1alpha1/clustergateway_types.go, pkg/apis/cluster/v1alpha1/clustergateway_types_secret.go, pkg/generated/clientset/versioned/typed/cluster/v1alpha1/clustergateway_expansion.go
- Fix: build tags from `vela` to `secret`
- Fix: move cluster secret label key out for external use
=> Fix: build tags and label key position

.gitignore, Makefile, README.md, e2e/benchmark/configmap.go, e2e/benchmark/e2e_test.go, e2e/e2e.go, e2e/e2e_test.go, e2e/framework/context.go, e2e/framework/framework.go, e2e/framework/scheme.go, e2e/kubernetes/e2e_test.go, e2e/kubernetes/non_resource.go, e2e/roundtrip/clustergateway.go, e2e/roundtrip/e2e_test.go, go.mod
=> Feat: e2e and benchmark results

pkg/apis/cluster/v1alpha1/printer.go
```shell
$ KUBECONFIG=hack/local.kubeconfig kubectl get clustergateways
NAME          PROVIDER   CREDENTIAL-TYPE       ENDPOINT-TYPE
vela-dev                 ServiceAccountToken   ClusterProxy
vela-prod                ServiceAccountToken   ClusterProxy
zuoxiu-kind              ServiceAccountToken   ClusterProxy
```
=> Feat: Better printer

charts/addon-manager/Chart.yaml, charts/addon-manager/templates/clusterroles.yaml, charts/addon-manager/values.yaml, pkg/addon/controllers/installer.go, pkg/event/secret_handler.go
=> Bugfix: Watch secret event from managed sa

charts/addon-manager/values.yaml, pkg/addon/agent/addon.go
=> By default ensure vela permission for managed sa

Makefile, charts/addon-manager/templates/clustergatewayconfiguration.yaml, charts/addon-manager/values.yaml, cmd/addon-manager/main.go, pkg/addon/controllers/installer.go, pkg/apis/cluster/v1alpha1/transport.go, pkg/event/apiservice_handler.go, pkg/event/secret_handler.go
=> Feat(addon-manager): Ensure and adopt exisiting cluster-gateway deployment 

.github/workflows/go-postsubmit.yml, Makefile
=> gh-action: post submit build & push latest image

Makefile
=> Fixes make image cmd path

.github/workflows/go-postsubmit.yml
=> gh-action: fix login domain

.github/workflows/go-postsubmit.yml, .github/workflows/go-release.yml
=> gh-action: releases-job

charts/addon-manager/Chart.yaml, charts/addon-manager/values.yaml
=> Bump chart v1.1.8

pkg/addon/controllers/installer.go
=> Underpin gateway deployment availability

go.mod, go.sum
=> Chore: Using official go mod path for managed-serviceaccount

README.md
=> Doc: Clarify OCM integration

README.md
Signed-off-by: zhukunshuai <jookunshuai@gmail.com>
=> Fix 'Run Local' docs link in README.md

e2e/benchmark/configmap.go
1、get managed cluster "kube-system"
2、list managed cluster 100 namespace
=> add Get request benchmark

cmd/apiserver/main.go, pkg/config/args_log.go
Add logging arguments for cluster-gateway.
Fixes https://github.com/oam-dev/cluster-gateway/issues/104.
=> Feat: add log args

charts/cluster-gateway/Chart.yaml
=> Feat: upgrade chart version to v1.6.0

cmd/apiserver/main.go, pkg/config/args_useragent.go
=> Feat: add support for specifying user agent

.github/workflows/go-release.yml
=> Feat: add registry push to acr.kubevela.net

README.md, cmd/apiserver/main.go, e2e/benchmark/configmap.go, examples/client-identity-exchanger/config.yaml, pkg/apis/cluster/v1alpha1/clustergateway_proxy.go, pkg/apis/cluster/v1alpha1/clustergateway_proxy_configuration.go, pkg/apis/cluster/v1alpha1/clustergateway_proxy_configuration_test.go, pkg/apis/cluster/v1alpha1/clustergateway_proxy_test.go, pkg/apis/cluster/v1alpha1/clustergateway_types.go, pkg/apis/cluster/v1alpha1/clustergateway_types_secret.go, pkg/apis/proxy/v1alpha1/groupversion_info.go, pkg/config/args_proxyconfig.go, pkg/generated/clientset/versioned/scheme/register.go, pkg/util/singleton/loopback.go
Implement #120, except:
1. priority is not implemented. The implicit priority for the rules is the lower index rule will have higher priority. Cluster configuration will have higher priority than global configuration.
2. ExternalIdentityExchanger is not implemented, but interfaces are left for future development.
=> Feat: support client identity exchange

charts/addon-manager/Chart.yaml
=> Chore: upgrade chart version to 1.7.0

charts/cluster-gateway/Chart.yaml
=> Chore: upgrade cluster-gateway chart version

.github/workflows/build-image.yml, .github/workflows/go-release.yml, cmd/apiserver/Dockerfile
Support building multi-arch image to ghcr and acr.
=> Feat: add release action for ghcr & acr image

pkg/apis/cluster/v1alpha1/clustergateway_types.go, pkg/apis/cluster/v1alpha1/clustergateway_types_secret.go, pkg/apis/cluster/v1alpha1/transport.go, pkg/apis/cluster/v1alpha1/transport_test.go
=> Feat: support proxy-url
